version: '3'

services:
    db:
        image: postgres:latest
        restart: always
    web:
        build: .
        restart: always
        ports:
          - 8080:8080
        volumes:
          - /static:/src/static_root
          - /nginx:/src/nginx
        depends_on:
          - db
        environment:
          - DEBUG=False
    nginx:
        image: nginx:latest
        restart: always
        network_mode: "host"
        volumes:
          - /static:/public/static:ro
          - /nginx:/etc/nginx/conf.d:ro
          - /docker/nginx/www/:/var/www:ro
          - /certs/letsencrypt:/etc/letsencrypt:ro
          - /var/run/docker.sock:/tmp/docker.sock:ro
        depends_on:
          - web
    proxy:
        image: imjacobclark/cors-container
        restart: always
        ports:
          - 127.0.0.1:8000:3000
