version: '3'

services:
    db:
        image: postgres:latest
    web:
        build: .
        ports:
          - "8080:8080"
        volumes:
          - /static:/src/static_root
        depends_on:
          - db
        environment:
          - DEBUG=False
    nginx:
        image: nginx:latest
        ports:
          - "80:80"
        volumes:
          - ./nginx:/etc/nginx/conf.d
          - /static:/public/static
          - /certs:/etc/letsencrypt
          - /certs-data:/data/letsencrypt
        depends_on:
          - web
